#define PICO_DEFAULT_UART 0
#define PICO_DEFAULT_UART_TX_PIN 0
#define PICO_DEFAULT_UART_RX_PIN 1
#define PICO_DEFAULT_UART_BAUD_RATE 1000000

#define PICO_DEFAULT_LED_PIN 25

#define PICO_FLASH_SPI_CLKDIV 2
#define PICO_FLASH_SIZE_BYTES (2 * 1024 * 1024)

#define PICO_SMPS_MODE_PIN 23

#define PICO_FLOAT_SUPPORT_ROM_V1 1
#define PICO_DOUBLE_SUPPORT_ROM_V1 1

